### PR TITLE
fix: web app using AdvertisingProvider crashed when rendered on the server side

### LINKED ISSUE #48: fix: “Window is not defined” error when rendering on the server
When using beta version 4.0.0-beta.1, which makes Prebid optional, a webapp will crash when the AdvertisingProvider component is rendered on the server side.

### PR DESCRIPTION
**Pull request by pahund**
* Fixes issue #48
* This change has been published to the public npm registry as version: `4.0.0-beta.2`

### CODE REVIEW

File: src/Advertising.js [hunk 1]
```diff
@@ -11,16 +11,13 @@ export default class Advertising {
     this.customEventCallbacks = {};
     this.customEventHandlers = {};
     this.queue = [];
-    this.isPrebidUsed = typeof window.pbjs !== 'undefined';
```
Comment (pahund) [inline src/Advertising.js:14]: this is what caused the crash when using react-advertising on the server: we can't assume there is a `window` object when the class is constructed. I've fixed it by moving the check for Prebid being used to the init method, which will only run client-side

**Review by filipecosta01 — APPROVED** [review]
